// 16-slot categorical color sets, one per theme id. Each set is a 16-element
// tuple indexed 0..15 in the canonical ANSI/xterm slot ORDER (0 black, 1 red,
// 2 green, 3 yellow, 4 blue, 5 magenta, 6 cyan, 7 white, then 8..15 the bright
// eight). The set is a per-theme CATEGORICAL palette (log levels, syntax, diff
// add/remove, chart series, tag/badge colors: eight hues x two intensities).
//
// Slots are addressed by INDEX, not name: after per-theme tuning a slot's hue
// may not match its ANSI name (e.g. dark's slot 3 holds the app's orange, slot
// 13 holds pink), so the names would lie - the index is the honest handle. The
// generator still derives slots from each theme's --red/--green/... internally
// (below); the slot NAMES survive only as the fixed emit ORDER.
//
// Sets marked "hand-tuned" were authored by eye (Moonpool). The rest are
// generated by tools/gen-ansi.py from each theme's own palette in themes.css
// and contrast-checked against that theme's ground; regenerate with:
//     python tools/gen-ansi.py
// Editing a generated set by hand is fine - add its id to HAND_TUNED in the
// script so a later run preserves it.
export type AnsiPalette = readonly [
  string, string, string, string, string, string, string, string,
  string, string, string, string, string, string, string, string,
];

export const ANSI: Record<string, AnsiPalette> = {
  // Hand-tuned (Moonpool).
  dark: [
    "#484f58", "#ff7b72", "#3fb950", "#d29922",
    "#58a6ff", "#bc8cff", "#39c5cf", "#b1bac4",
    "#6e7681", "#ffa198", "#56d364", "#e3b341",
    "#79c0ff", "#d2a8ff", "#56d4dd", "#ffffff",
  ],
  // Hand-tuned (Moonpool).
  light: [
    "#24292f", "#cf222e", "#1a7f37", "#9a6700",
    "#0969da", "#8250df", "#1b7c83", "#6e7781",
    "#57606a", "#a40e26", "#116329", "#7d4e00",
    "#0550ae", "#6639ba", "#1b7c83", "#24292f",
  ],
  // Hand-tuned (Moonpool).
  purple: [
    "#3a2f4d", "#ff7b9c", "#8ce0b0", "#e6c07b",
    "#8a7bff", "#c792ea", "#7fd0e0", "#c8bfe0",
    "#6b5b8a", "#ff9dbb", "#a8ecc6", "#f0d29a",
    "#a89bff", "#dcaef5", "#a0e2ef", "#f2eeff",
  ],
  // Hand-tuned (Moonpool).
  ocean: [
    "#2a3f52", "#ff8a80", "#5fd0b0", "#e6c86b",
    "#5fa8e6", "#a99be6", "#4fd0d8", "#b0c4d4",
    "#4f6a80", "#ffab9e", "#84e6c9", "#f0d98a",
    "#82c0f0", "#c2b5f0", "#79e2e8", "#e6f1f7",
  ],
  // Hand-tuned (Moonpool).
  matrix: [
    "#153d1a", "#e06b5c", "#33ff66", "#b8e05c",
    "#4fbf7f", "#7fdf8f", "#5fe6a0", "#9ce0a8",
    "#2f5c3a", "#ff8c7a", "#66ff8f", "#d4f07a",
    "#78d99e", "#a3efad", "#8cf5c0", "#d6ffdf",
  ],
  // Hand-tuned (Moonpool).
  amber: [
    "#4a3524", "#ff8a5c", "#c0c05c", "#ffb638",
    "#d19a5c", "#e6996b", "#d4b06b", "#e0c4a0",
    "#7a5c3a", "#ffab7a", "#d6d67a", "#ffcf6b",
    "#e6b87a", "#f0b58c", "#eacf8c", "#fff0d6",
  ],
  // Hand-tuned (Moonpool).
  rose: [
    "#4d2f38", "#ff6b8a", "#8cd0a0", "#e6bb7b",
    "#c98ab0", "#f28fb0", "#d99ac4", "#e0c0cc",
    "#7a5060", "#ff8fa8", "#a8e0bb", "#f0d29a",
    "#e0a8c4", "#ffabc4", "#efb8da", "#ffe6ee",
  ],
  // Hand-tuned (Moonpool).
  nord: [
    "#495165", "#bf616a", "#a3be8c", "#ebcb8b",
    "#81a1c1", "#b48ead", "#88c0d0", "#e5e9f0",
    "#5e6a83", "#bf616a", "#a3be8c", "#ebcb8b",
    "#81a1c1", "#b48ead", "#8fbcbb", "#eceff4",
  ],
  // Hand-tuned (Moonpool).
  dracula: [
    "#46485d", "#ff5555", "#50fa7b", "#f1fa8c",
    "#bd93f9", "#ff79c6", "#8be9fd", "#f8f8f2",
    "#6272a4", "#ff6e6e", "#69ff94", "#ffffa5",
    "#d6acff", "#ff92df", "#a4ffff", "#ffffff",
  ],
  // Hand-tuned (Moonpool).
  gruvbox: [
    "#474747", "#df2720", "#98971a", "#d79921",
    "#458588", "#b16286", "#689d6a", "#a89984",
    "#928374", "#fb4934", "#b8bb26", "#fabd2f",
    "#83a598", "#d3869b", "#8ec07c", "#ebdbb2",
  ],
  // Hand-tuned (Moonpool).
  solarized: [
    "#0a4b5c", "#dc322f", "#859900", "#b58900",
    "#268bd2", "#d33682", "#2aa198", "#eee8d5",
    "#006a85", "#cb4b16", "#607880", "#657b83",
    "#839496", "#6c71c4", "#93a1a1", "#fdf6e3",
  ],
  // Hand-tuned (Moonpool).
  crimson: [
    "#4d2830", "#ff5c6b", "#9cc78a", "#e6b56b",
    "#d17b8a", "#e67b8f", "#d18a9c", "#e0b8bf",
    "#7a4650", "#ff7d8a", "#b6d9a3", "#f0cd8a",
    "#e6a3ad", "#ffa3b0", "#e6abbb", "#ffe0e4",
  ],
  // Hand-tuned (Moonpool).
  mint: [
    "#1f3d33", "#c0362e", "#0f8a5f", "#9a7200",
    "#1f7a8c", "#8a3f9c", "#0e8a7a", "#527a6e",
    "#3a5c50", "#a02820", "#0a6e4a", "#7d5c00",
    "#175f6e", "#6e2f7d", "#0a6e60", "#1f3d33",
  ],
  // Hand-tuned (Moonpool).
  paper: [
    "#33302a", "#b03a2e", "#5a7d2a", "#96690f",
    "#2e6b8a", "#8a4a7d", "#1f7a70", "#6e665a",
    "#524c40", "#943024", "#476420", "#7d570a",
    "#25546e", "#6e3a63", "#186259", "#33302a",
  ],
  // Hand-tuned (Moonpool).
  sky: [
    "#1f3a4d", "#c0362e", "#2a7d4a", "#96690f",
    "#1565c0", "#7d3f9c", "#0e7a8c", "#527088",
    "#3a566e", "#a02820", "#20643a", "#7d570a",
    "#0d4f9c", "#632f7d", "#0a6070", "#1f3a4d",
  ],
  // Hand-tuned (Moonpool).
  lavender: [
    "#352f4d", "#b83a54", "#3a7d5a", "#8a6a0f",
    "#4a4fc0", "#8a3f9c", "#2a6a8c", "#6e6688",
    "#4f486e", "#9c2840", "#2a6448", "#7d570a",
    "#3a3f9c", "#6e2f7d", "#215470", "#352f4d",
  ],
  // Hand-tuned (Moonpool).
  sage: [
    "#2e3a2a", "#b03a2e", "#3a7d2e", "#8a6a0f",
    "#2e6b7d", "#7d4a6e", "#1f7a5f", "#63705a",
    "#4a5642", "#943024", "#2a6420", "#7d570a",
    "#255466", "#633a57", "#186249", "#2e3a2a",
  ],
  // Generated from the bubblegum palette.
  bubblegum: [
    "#36262f", "#a31534", "#9d1b71", "#a0182f",
    "#235295", "#b00778", "#21838c", "#8f5b76",
    "#5d4653", "#790b23", "#751053", "#770d1f",
    "#153b6f", "#7f0557", "#15686f", "#36262f",
  ],
  // Generated from the cottoncandy palette.
  cottoncandy: [
    "#2c2636", "#a71026", "#382890", "#892f70",
    "#0768b0", "#892f70", "#0736b0", "#745b8f",
    "#4f465d", "#7d0818", "#26196c", "#671e52",
    "#054b7f", "#671e52", "#05277f", "#2c2636",
  ],
  // Generated from the vaporwave palette.
  vaporwave: [
    "#4c4064", "#f14b75", "#4be6f1", "#f14bac",
    "#4be6f1", "#f14b75", "#4bb4f1", "#c2bcc8",
    "#6a5c84", "#f684a1", "#84eef6", "#f684c6",
    "#84eef6", "#f684a0", "#84ccf6", "#f5f4f6",
  ],
  // Generated from the sunset palette.
  sunset: [
    "#64405c", "#f14b4b", "#f1bf4b", "#f1854b",
    "#6294da", "#da62da", "#62d0da", "#c8c1bc",
    "#845c7c", "#f68484", "#f6d384", "#f6ac84",
    "#90b5ea", "#ea90ea", "#90e2ea", "#f6f5f4",
  ],
  // Generated from the cyberpunk palette.
  cyberpunk: [
    "#404064", "#f14b72", "#4bf1b3", "#f1e84b",
    "#6294da", "#da62da", "#4bf1e5", "#bcc6c8",
    "#5c5c84", "#f6849f", "#84f6cb", "#f6ef84",
    "#90b5ea", "#ea90ea", "#84f6ed", "#f4f6f6",
  ],
  // Generated from the lofi palette.
  lofi: [
    "#554865", "#ce776e", "#9f79c3", "#d49b68",
    "#6294da", "#9f79c3", "#79c3af", "#c8c2bc",
    "#6e6080", "#e19e98", "#bea0da", "#e6ba94",
    "#90b5ea", "#bea0da", "#a0daca", "#f6f5f4",
  ],
  // Generated from the coffee palette.
  coffee: [
    "#5d493c", "#d17f6b", "#c6ac76", "#d4a668",
    "#6294da", "#da62da", "#62d0da", "#c8c3bc",
    "#846c5c", "#e4a596", "#dcc79d", "#e6c294",
    "#90b5ea", "#ea90ea", "#90e2ea", "#f6f5f4",
  ],
  // Generated from the sakura palette.
  sakura: [
    "#36262d", "#93254d", "#4f8235", "#8b2d38",
    "#235295", "#a01721", "#238b95", "#8f5b6a",
    "#5d4650", "#6e1737", "#376222", "#681d25",
    "#153b6f", "#780d14", "#15686f", "#36262d",
  ],
  // Generated from the deepsea palette.
  deepsea: [
    "#3c4c5d", "#f14b63", "#5edece", "#4bbef1",
    "#4bbef1", "#da62da", "#5ec8de", "#bcc5c8",
    "#5c6f84", "#f68494", "#8dece0", "#84d3f6",
    "#84d3f6", "#ea90ea", "#8ddcec", "#f4f5f6",
  ],
  // Generated from the monokai palette.
  monokai: [
    "#535742", "#f14b87", "#b7e755", "#e1d45b",
    "#6294da", "#f14b4f", "#62d0da", "#c8c8bc",
    "#797d64", "#f684ad", "#cff387", "#efe58b",
    "#90b5ea", "#f68487", "#90e2ea", "#f6f6f4",
  ],
  // Generated from the tokyonight palette.
  tokyonight: [
    "#44476a", "#f14b6a", "#4b80f1", "#864bf1",
    "#4b80f1", "#864bf1", "#5e61f3", "#bcbec8",
    "#5c5f84", "#f68499", "#84a8f6", "#ac84f6",
    "#84a8f6", "#ac84f6", "#8486f6", "#f4f4f6",
  ],
  // Generated from the forest palette.
  forest: [
    "#3c5d49", "#da8e62", "#79c37d", "#c1cb72",
    "#6294da", "#da62da", "#62d0da", "#bfc8bc",
    "#5c846c", "#eab090", "#9fdaa2", "#d8df9a",
    "#90b5ea", "#ea90ea", "#90e2ea", "#f4f6f4",
  ],
  // Generated from the slate palette.
  slate: [
    "#404e64", "#f14b86", "#4bbcf1", "#799cc3",
    "#799bc3", "#f14b4f", "#4b8af1", "#bcc1c8",
    "#5c6c84", "#f684ac", "#84d1f6", "#a0bbda",
    "#a0bada", "#f68486", "#84aff6", "#f4f5f6",
  ],
  // Generated from the sepia palette.
  sepia: [
    "#363026", "#943e23", "#728235", "#936e25",
    "#235295", "#952395", "#238b95", "#8f7e5b",
    "#5d5446", "#6f2b16", "#556222", "#6e5116",
    "#153b6f", "#6f156f", "#15686f", "#363026",
  ],
  // Generated from the peach palette.
  peach: [
    "#362b26", "#a1171b", "#a74011", "#ac570b",
    "#235295", "#952395", "#238b95", "#8f6f5b",
    "#5d4d46", "#780d10", "#7c2d08", "#7f3f05",
    "#153b6f", "#6f156f", "#15686f", "#362b26",
  ],
  // Generated from the reef palette.
  reef: [
    "#3c595d", "#f1a64b", "#4bf1e2", "#6ece7d",
    "#4bf1e2", "#da62da", "#4bcff1", "#bcc8c6",
    "#5c7f84", "#f6c284", "#84f6eb", "#98e2a3",
    "#84f6eb", "#ea90ea", "#84def6", "#f4f6f6",
  ],
  // Generated from the graphite palette.
  graphite: [
    "#44505f", "#f19e4b", "#4cf0e0", "#95ca72",
    "#4cf0e0", "#da62da", "#4ccff0", "#bcc2c8",
    "#606e81", "#f6bc84", "#84f6ea", "#b6df9b",
    "#84f6ea", "#ea90ea", "#84dff6", "#f4f5f6",
  ],
  // Generated from the flux palette.
  flux: [
    "#44505f", "#f14baa", "#4cf0e0", "#f1a04b",
    "#4cf0e0", "#f14b73", "#4ccff0", "#bcc2c8",
    "#606e81", "#f684c5", "#84f6ea", "#f6be84",
    "#84f6ea", "#f6849f", "#84dff6", "#f4f5f6",
  ],
  // Generated from the apricot palette.
  apricot: [
    "#362c26", "#a91c0f", "#b04207", "#ad6e0b",
    "#235295", "#952395", "#238b95", "#8f715b",
    "#5d4f46", "#7e1107", "#7f2f05", "#7f5005",
    "#153b6f", "#6f156f", "#15686f", "#362c26",
  ],
  // Generated from the butter palette.
  butter: [
    "#363326", "#9a501e", "#9d851a", "#8f881e",
    "#235295", "#952395", "#238b95", "#8f875b",
    "#5d5946", "#733911", "#76630f", "#726b13",
    "#153b6f", "#6f156f", "#15686f", "#363326",
  ],
  // Generated from the pistachio palette.
  pistachio: [
    "#2f3626", "#955c22", "#568830", "#78832b",
    "#235295", "#952395", "#238b95", "#738f5b",
    "#535d46", "#704315", "#3d661f", "#5f681d",
    "#153b6f", "#6f156f", "#15686f", "#2f3626",
  ],
  // Generated from the seafoam palette.
  seafoam: [
    "#263633", "#a42714", "#318676", "#588335",
    "#235295", "#952395", "#317e86", "#5b8f86",
    "#465d59", "#7a1a0a", "#206557", "#3f6222",
    "#153b6f", "#6f156f", "#205e65", "#263633",
  ],
  // Generated from the cornflower palette.
  cornflower: [
    "#262936", "#a41442", "#183f9f", "#34199f",
    "#073eb0", "#a41614", "#3607b0", "#5b6c8f",
    "#464b5d", "#7a0a2e", "#0e2c77", "#230e76",
    "#052d7f", "#7a0c0a", "#27057f", "#262936",
  ],
  // Generated from the linen palette.
  linen: [
    "#363126", "#825135", "#698235", "#876e31",
    "#235295", "#952395", "#238b95", "#8f7d5b",
    "#5d5546", "#623a22", "#4d6222", "#65511f",
    "#153b6f", "#6f156f", "#15686f", "#363126",
  ],
  // Generated from the oat palette.
  oat: [
    "#362f26", "#884b30", "#826f35", "#8a7c2d",
    "#235295", "#952395", "#21838c", "#8f7c5b",
    "#5d5446", "#66351f", "#625222", "#685c1d",
    "#153b6f", "#6f156f", "#15686f", "#362f26",
  ],
  // Generated from the greige palette.
  greige: [
    "#363026", "#824b35", "#826935", "#826435",
    "#235295", "#952395", "#21838c", "#8f7a5b",
    "#5d5446", "#623522", "#624d22", "#624922",
    "#153b6f", "#6f156f", "#15686f", "#363026",
  ],
  // Generated from the stone palette.
  stone: [
    "#363326", "#824935", "#768235", "#827035",
    "#235295", "#952395", "#21838c", "#857d65",
    "#5d5946", "#623322", "#586222", "#625322",
    "#153b6f", "#6f156f", "#15686f", "#363326",
  ],
  // Generated from the taupe palette.
  taupe: [
    "#584e41", "#d18b6c", "#c3ac79", "#d0aa6c",
    "#6294da", "#da62da", "#62d0da", "#c8c3bc",
    "#7f7261", "#e3ae96", "#dac8a0", "#e3c697",
    "#90b5ea", "#ea90ea", "#90e2ea", "#f6f5f4",
  ],
  // Generated from the ash palette.
  ash: [
    "#373c43", "#fac1bd", "#4bf1e2", "#f1f14b",
    "#4bf1e2", "#efbdef", "#7adbf5", "#f4f5f6",
    "#26282c", "#fbd3d0", "#84f6eb", "#f6f584",
    "#84f6eb", "#f5ccf5", "#a0e5f8", "#f4f5f6",
  ],
  // Generated from the dusk palette.
  dusk: [
    "#78639c", "#f4678b", "#4bdaf1", "#f35ec3",
    "#4bdaf1", "#f35ec3", "#4ba8f1", "#c0bcc8",
    "#8f81a7", "#f684a1", "#84e6f6", "#f684d1",
    "#84e6f6", "#f684d1", "#84c4f6", "#f4f4f6",
  ],
  // Generated from the terracotta palette.
  terracotta: [
    "#3e2e28", "#f3aaa5", "#f1b14b", "#f5ad7a",
    "#a4c1ea", "#eaa4ea", "#62d0da", "#e3e0dd",
    "#b8a299", "#f8b9b5", "#f6ca84", "#f6b98d",
    "#b2ccf0", "#f0b2f0", "#90e2ea", "#f6f5f4",
  ],
  // Generated from the steelblue palette.
  steelblue: [
    "#242d38", "#f8a0a0", "#58e4d6", "#a2cb71",
    "#58e4d6", "#eaa4ea", "#58c8e4", "#dde0e3",
    "#93a2b4", "#f9b3b3", "#89f0e6", "#c0e09a",
    "#89f0e6", "#f0b2f0", "#89dcf0", "#f4f5f6",
  ],
  // Generated from the moss palette.
  moss: [
    "#253121", "#eaab85", "#85de5f", "#d0d765",
    "#9cbbe8", "#eaa4ea", "#62d0da", "#dcdfd8",
    "#90ab87", "#f1b693", "#aaec8d", "#e3e892",
    "#a9c6ef", "#f0b2f0", "#90e2ea", "#f5f6f4",
  ],
  // Generated from the clay palette.
  clay: [
    "#4d4238", "#f1d9d0", "#e3d8c0", "#ebd7b8",
    "#cdddf3", "#f3cdf3", "#a4e4ea", "#f6f5f4",
    "#342e28", "#f7e5de", "#eee6d3", "#f3e5ce",
    "#dde8f8", "#f8ddf8", "#c3f0f4", "#f6f5f4",
  ],
  // Generated from the fog palette.
  fog: [
    "#262c36", "#991f1f", "#0a5c66", "#6c4c0f",
    "#055761", "#8c218c", "#0d5282", "#687382",
    "#424a57", "#721212", "#054e56", "#66470a",
    "#044f58", "#6f156f", "#084d7d", "#262c36",
  ],
  // Generated from the dustyrose palette.
  dustyrose: [
    "#302128", "#7f2e45", "#21504c", "#83343b",
    "#21504e", "#8b2d31", "#26505e", "#8f5b68",
    "#513d46", "#651f33", "#1b4b47", "#632227",
    "#1b4b49", "#681d20", "#204b5b", "#302128",
  ],
  // Generated from the mauve palette.
  mauve: [
    "#41374d", "#f7bfd1", "#b8caf4", "#dac1ec",
    "#b8caf4", "#dac1ec", "#cacaf7", "#f5f4f6",
    "#28232f", "#fac7d7", "#c8d6f9", "#e3cef2",
    "#c8d6f9", "#e3cef2", "#d2d1fa", "#f5f4f6",
  ],
  // Generated from the amethyst palette.
  amethyst: [
    "#4e4064", "#d64bf1", "#a44bf1", "#a04bf1",
    "#6294da", "#f14bd5", "#62d0da", "#c0bcc8",
    "#6c5c84", "#e384f6", "#c184f6", "#be84f6",
    "#90b5ea", "#f684e2", "#90e2ea", "#f4f4f6",
  ],
  // Generated from the ultraviolet palette.
  ultraviolet: [
    "#484064", "#f14bd4", "#774bf1", "#a74bf1",
    "#5e4bf1", "#f14b9d", "#62d0da", "#bebcc8",
    "#655c84", "#f684e2", "#a284f6", "#c384f6",
    "#9184f6", "#f684bc", "#90e2ea", "#f4f4f6",
  ],
  // Generated from the orchid palette.
  orchid: [
    "#564064", "#f14ba0", "#bb4bf1", "#b64bf1",
    "#6294da", "#bb4bf1", "#62d0da", "#c5bcc8",
    "#755c84", "#f684be", "#d184f6", "#cd84f6",
    "#90b5ea", "#d184f6", "#90e2ea", "#f5f4f6",
  ],
  // Generated from the rosewood palette.
  rosewood: [
    "#6a4444", "#e75584", "#f1ad4b", "#f1804b",
    "#6294da", "#e75755", "#62d0da", "#c8bfbc",
    "#845c5c", "#f387aa", "#f6c784", "#f6a884",
    "#90b5ea", "#f38887", "#90e2ea", "#f6f4f4",
  ],
  // Generated from the ember palette.
  ember: [
    "#5d403c", "#f14b83", "#f19b4b", "#f1774b",
    "#6294da", "#f14b4c", "#62d0da", "#c8c0bc",
    "#84625c", "#f684aa", "#f6bb84", "#f6a284",
    "#90b5ea", "#f68484", "#90e2ea", "#f6f4f4",
  ],
  // Generated from the sienna palette.
  sienna: [
    "#5d483c", "#db617b", "#eca351", "#e58258",
    "#6294da", "#da62da", "#62d0da", "#c8c2bc",
    "#846b5c", "#ea8fa2", "#f6c184", "#f1a888",
    "#90b5ea", "#ea90ea", "#90e2ea", "#f6f5f4",
  ],
  // Generated from the glacier palette.
  glacier: [
    "#3c495d", "#6254f2", "#4bd5f1", "#4ba1f1",
    "#4b9cf1", "#da62da", "#4ba3f1", "#bcc2c8",
    "#5c6c84", "#8d84f6", "#84e2f6", "#84bff6",
    "#84bbf6", "#ea90ea", "#84c0f6", "#f4f5f6",
  ],
  // Generated from the tide palette.
  tide: [
    "#3c525d", "#804bf1", "#4bf1e6", "#4b9ff1",
    "#4b9ff1", "#b74bf1", "#4bcbf1", "#bcc6c8",
    "#5c7784", "#a884f6", "#84f6ee", "#84bdf6",
    "#84bdf6", "#ce84f6", "#84dcf6", "#f4f6f6",
  ],
  // Generated from the aurora palette.
  aurora: [
    "#404764", "#984bf1", "#4bf1c5", "#4ba8f1",
    "#4ba8f1", "#d04bf1", "#4bebf1", "#bcbfc8",
    "#5c6484", "#b984f6", "#84f6d8", "#84c3f6",
    "#84c3f6", "#df84f6", "#84f2f6", "#f4f4f6",
  ],
  // Generated from the pop palette.
  pop: [
    "#262636", "#b00729", "#0798a6", "#b00786",
    "#0797a6", "#b00786", "#076eb0", "#5b5b8f",
    "#46465d", "#7f051e", "#05747f", "#7f0561",
    "#05747f", "#7f0561", "#054f7f", "#262636",
  ],
  // Generated from the citrus palette.
  citrus: [
    "#363226", "#b04307", "#439d07", "#a67f07",
    "#235295", "#952395", "#238b95", "#8f855b",
    "#5d5846", "#7f3005", "#367f05", "#7f6105",
    "#153b6f", "#6f156f", "#15686f", "#363226",
  ],
  // Generated from the candy palette.
  candy: [
    "#332636", "#0724b0", "#b00768", "#730daa",
    "#072cb0", "#730daa", "#238b95", "#8f5b80",
    "#59465d", "#051a7f", "#7f054b", "#54057f",
    "#05207f", "#54057f", "#15686f", "#332636",
  ],
  // Generated from the volt palette.
  volt: [
    "#263626", "#b00728", "#079d30", "#789306",
    "#235295", "#952395", "#238b95", "#5b8f5b",
    "#465d47", "#7f051d", "#057f27", "#687f05",
    "#153b6f", "#6f156f", "#15686f", "#263626",
  ],
  // Generated from the azure palette.
  azure: [
    "#262c36", "#b00750", "#0773b0", "#3407b0",
    "#0773b0", "#b00718", "#0717b0", "#5b788f",
    "#464f5d", "#7f053a", "#05537f", "#26057f",
    "#05537f", "#7f0511", "#05107f", "#262c36",
  ],
};

// Resolve a color set for a RESOLVED theme id (never "auto"); falls back to
// dark, so a theme with no set of its own still renders.
export function ansiFor(id: string): AnsiPalette {
  return ANSI[id] ?? ANSI.dark;
}

// The same set under xterm's named ITheme color slots (xterm wants keys, not an
// index). Spread into the terminal theme: `{ ...xtermColors(id) }`.
const XTERM_SLOTS = [
  "black", "red", "green", "yellow", "blue", "magenta", "cyan", "white",
  "brightBlack", "brightRed", "brightGreen", "brightYellow",
  "brightBlue", "brightMagenta", "brightCyan", "brightWhite",
] as const;

export function xtermColors(id: string): Record<(typeof XTERM_SLOTS)[number], string> {
  const set = ansiFor(id);
  return Object.fromEntries(XTERM_SLOTS.map((k, i) => [k, set[i]])) as Record<
    (typeof XTERM_SLOTS)[number],
    string
  >;
}
