// Generated by build_set.py from picks.json. Edit those, not this.
//
// One 24 unit grid for every icon, drawn in currentColor, so an icon
// takes the colour of the text beside it and the weight the component
// sets. A few are filled rather than stroked and say so on the element.
// The union type is the point of the file: a misspelled name is a build
// error rather than an invisible icon.
export type SharedIconName =
  | "bullseye"
  | "chevron-left"
  | "chevron-right"
  | "clock"
  | "close"
  | "copy"
  | "flask"
  | "folder"
  | "home"
  | "info"
  | "layers"
  | "lock"
  | "maximize"
  | "maximize-round"
  | "more-horizontal"
  | "more-vertical"
  | "plus"
  | "refresh"
  | "save"
  | "search"
  | "sliders"
  | "target"
  | "trash-empty"
  | "user-star";

export const SHARED_PATHS: Record<SharedIconName, string> = {
  // MogStudio, src/lib/components/Icon.svelte
  "bullseye":
    `<circle cx="12" cy="12" r="9" /><circle cx="12" cy="12" r="3" />`,
  // chevron-right, mirrored
  "chevron-left":
    `<path d="M15 6l-6 6l6 6" />`,
  // MoonPool, src/lib/Sidebar.svelte
  "chevron-right":
    `<path d="M9 6l6 6-6 6" />`,
  // MusicPlayer, src/App.svelte
  "clock":
    `<circle cx="12" cy="12" r="9" /><path d="M12 7v5l3 2" />`,
  // MogStudio, src/lib/components/Icon.svelte
  "close":
    `<path d="M18 6 6 18" /><path d="m6 6 12 12" />`,
  // MusicPlayer, src/lib/TrackContextMenu.svelte
  "copy":
    `<path d="M9 9h9a1 1 0 0 1 1 1v9a1 1 0 0 1-1 1H9a1 1 0 0 1-1-1v-9a1 1 0 0 1 1-1z M5 15H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v1" />`,
  // MogStudio, src/lib/components/Icon.svelte
  "flask":
    `<path d="M9 3h6" /><path d="M10 3v6l-5 9a2 2 0 0 0 2 3h10a2 2 0 0 0 2-3l-5-9V3" /><path d="M6.5 15h11" />`,
  // MusicPlayer, src/App.svelte
  "folder":
    `<path d="M3 7a2 2 0 0 1 2 -2h4l2 2h8a2 2 0 0 1 2 2v8a2 2 0 0 1 -2 2H5a2 2 0 0 1 -2 -2z" />`,
  // Greedout, src/lib/Baseline.svelte
  "home":
    `<path d="M3 11.2 12 4l9 7.2M5.5 9.8V19a1 1 0 0 0 1 1H10v-5h4v5h3.5a1 1 0 0 0 1-1V9.8" />`,
  // FasterDB, FasterDBApp/src/App.svelte
  "info":
    `<circle cx="12" cy="12" r="9.3" /><path d="M12 10.8v5.4" /><circle cx="12" cy="7.65" r="0.9" fill="currentColor" stroke="none" />`,
  // MogStudio, src/lib/components/Icon.svelte
  "layers":
    `<path d="m12 2 9 5-9 5-9-5 9-5z" /><path d="m3 12 9 5 9-5" /><path d="m3 17 9 5 9-5" />`,
  // MusicPlayer, src/lib/TransitionsView.svelte
  "lock":
    `<rect x="5" y="11" width="14" height="10" rx="2" /><path d="M8 11V7a4 4 0 0 1 8 0v4" />`,
  // MoonPool, src/lib/Titlebar.svelte
  "maximize":
    `<rect x="5" y="5" width="14" height="14" />`,
  // MusicPlayer, src/App.svelte
  "maximize-round":
    `<rect x="4.8" y="4.8" width="14.4" height="14.4" rx="2" />`,
  // more-vertical, turned
  "more-horizontal":
    `<circle cy="12" cx="5" r="1.6" fill="currentColor" stroke="none" /><circle cy="12" cx="12" r="1.6" fill="currentColor" stroke="none" /><circle cy="12" cx="19" r="1.6" fill="currentColor" stroke="none" />`,
  // MusicPlayer, src/lib/TrackMenu.svelte
  "more-vertical":
    `<circle cx="12" cy="5" r="1.6" fill="currentColor" stroke="none" /><circle cx="12" cy="12" r="1.6" fill="currentColor" stroke="none" /><circle cx="12" cy="19" r="1.6" fill="currentColor" stroke="none" />`,
  // MoonPool, src/lib/Icon.svelte
  "plus":
    `<path d="M5 12h14" /><path d="M12 5v14" />`,
  // MoonPool, src/lib/Icon.svelte
  "refresh":
    `<path d="M21 12a9 9 0 1 1-2.64-6.36L21 8" /><path d="M21 3v5h-5" />`,
  // FasterDB, FasterDBApp/src/App.svelte
  "save":
    `<path d="M4.8 3.75h11.4L20.25 7.8v12.45a1.5 1.5 0 0 1-1.5 1.5H5.25a1.5 1.5 0 0 1-1.5-1.5V5.25a1.5 1.5 0 0 1 1.05-1.5z" /><path d="M8.25 3.75v5.25h6.75V3.75" /><path d="M7.5 21v-6.75h9V21" />`,
  // MogStudio, src/lib/components/Icon.svelte
  "search":
    `<circle cx="11" cy="11" r="7" /><path d="m21 21-4.3-4.3" />`,
  // MoonPool, src/lib/Icon.svelte
  "sliders":
    `<path d="M21 4h-7" /><path d="M10 4H3" /><path d="M21 12h-9" /><path d="M8 12H3" /><path d="M21 20h-5" /><path d="M12 20H3" /><path d="M14 2v4" /><path d="M8 10v4" /><path d="M16 18v4" />`,
  // MusicPlayer, src/App.svelte
  "target":
    `<circle cx="12" cy="12" r="9" /><circle cx="12" cy="12" r="2.4" /><path d="M12 3v3M12 18v3M3 12h3M18 12h3" />`,
  // MogStudio, src/lib/components/Icon.svelte
  "trash-empty":
    `<path d="M3 6h18" /><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6" /><path d="M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2" />`,
  // MusicPlayer, public/icons.svg
  "user-star":
    `<path d="M15 8a5 5 0 1 0-10 0 5 5 0 0 0 10 0" /><path d="M3 20a7 7 0 0 1 10.5-6.06m4.6 0.57 0.62 1.24c0.08 0.17 0.31 0.34 0.5 0.37l1.12 0.19c0.72 0.12 0.88 0.64 0.37 1.16l-0.87 0.88a0.77 0.77 0 0 0-0.18 0.64l0.25 1.08c0.2 0.86-0.26 1.19-1.01 0.74l-1.05-0.62a0.76 0.76 0 0 0-0.69 0l-1.05 0.62c-0.75 0.45-1.2 0.11-1.01-0.74l0.25-1.08a0.77 0.77 0 0 0-0.18-0.64l-0.87-0.87c-0.51-0.52-0.35-1.04 0.37-1.16l1.12-0.19a0.77 0.77 0 0 0 0.49-0.37l0.62-1.24c0.34-0.67 0.88-0.67 1.21 0" />`,
};
